language: python
python:
  - "2.7"
sudo: false
cache:
  pip: true
  directories:
    - node_modules
services:
  - postgresql
install:
  - "pip install -U pip wheel"
  - "nvm install 8"
  - "pip install -r requirements.txt -r requirements.test.txt"
before_script:
  - "cd client && npm install && cd .."
  - "cd client && ./node_modules/.bin/webpack --config webpack.prod.config.js && cd .."
  - "cp modernomad/local_settings.travis.py modernomad/local_settings.py"
script: ./manage.py test
notifications:
  slack:
    rooms:
      - embassy-network:joFu5a311yAWnrF7DQGKtl02#modernomad-notify
  email:
    recipients:
      - craig@enspiral.com
    on_success: change
    on_failure: always
