language: node_js
node_js:
 - 10
cache:
  npm: true
  directories:
    # cache folder with Cypress binary
    - ~/.cache
dist: xenial
install:
  - sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
  - npm ci
script:
 - script/test
 - docker-compose -f docker-compose.production.yml up -d
 - docker-compose -f docker-compose.production.yml run web ./manage.py migrate
 - docker-compose -f docker-compose.production.yml run web ./manage.py generate_test_data
 - $(npm bin)/cypress run --record --key 88257c2f-8d2e-464c-878b-650cace8563e
after_script:
# For debugging
- docker-compose -f docker-compose.production.yml logs
notifications:
  slack:
    rooms:
      - embassy-network:joFu5a311yAWnrF7DQGKtl02#modernomad-notify
  email:
    recipients:
      - craig@enspiral.com
    on_success: change
    on_failure: always
