version: "3.4"

services:
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - "DJANGO_SETTINGS_MODULE=modernomad.settings.local"
      - "DATABASE_URL=postgres://postgres@postgres/postgres"
      - "BROKER_URL=amqp://guest:guest@rabbitmq//"
      - "STRIPE_SECRET_KEY"
      - "STRIPE_PUBLISHABLE_KEY"
      - "MAILGUN_API_KEY"
    links:
      - postgres
      - rabbitmq
    volumes:
      - "./:/app"
  client:
    build: .
    working_dir: /app/client/
    command: node server.js
    ports:
      - "3000:3000"
    # Bind mount app directory, but leave node_modules intact
    volumes:
      - "./:/app"
      - "/app/client/node_modules"
  worker:
    build: .
    command: bin/celeryd
    environment:
      - "DJANGO_SETTINGS_MODULE=modernomad.settings.local"
      - "DATABASE_URL=postgres://postgres@postgres/postgres"
      - "BROKER_URL=amqp://guest:guest@rabbitmq//"
      - "STRIPE_SECRET_KEY"
      - "STRIPE_PUBLISHABLE_KEY"
      - "MAILGUN_API_KEY"
    links:
      - postgres
      - rabbitmq
    volumes:
      - "./:/app"
  rabbitmq:
    image: rabbitmq
  postgres:
    image: postgres
